// [snowpack] add styles to the page (skip if no document exists)
if (typeof document !== 'undefined') {
  const code = "h1 {\n  text-align: center;\n}\na {\n  text-decoration: none;\n}\n.option {\n  display: flex;\n  justify-content: center;\n  align-items: center;\n  margin: 6px;\n  border: 1px solid #cbcbcb;\n  padding: 8px;\n  border-radius: 8px;\n}\n.option label {\n  padding: 0 6px;\n  font-weight: bold;\n}\n\n.option input {\n  display: block;\n  outline: none;\n  padding: 4px;\n  border: none;\n  font-size: 16px;\n  width: 90px;\n  text-align: center;\n}\n.warpper {\n  width: 300px;\n  height: 170px;\n\n  border-radius: 10px;\n  margin: 1rem auto;\n  background-color: #fbfbfb;\n  box-shadow: 0 10px 10px -5px #00000055;\n  display: flex;\n  justify-content: center;\n  align-items: center;\n  cursor: pointer;\n  transition: background-color cubic-bezier(0.075, 0.82, 0.165, 1) 300ms;\n}\ninput {\n  display: none;\n}\n.icon {\n  width: 30px;\n  display: block;\n}\n.label {\n  display: flex;\n  align-items: center;\n  justify-content: center;\n  flex-direction: column;\n  color: #2196f3;\n  transition: color cubic-bezier(0.075, 0.82, 0.165, 1) 300ms;\n  cursor: pointer;\n}\nvideo {\n  margin: 1rem auto;\n  display: block;\n  width: 290px;\n}\n.warpper:hover {\n  background-color: #2196f3;\n}\n.warpper:hover .label {\n  color: #fbfbfb;\n}\n.result {\n  display: flex;\n  flex-direction: column;\n  justify-content: center;\n  align-items: center;\n}\nbutton,\na.btn {\n  box-shadow: 0 0 10px 3px #0000001f;\n  border: none;\n  background: #2196f3;\n  padding: 8px 2rem;\n  font-size: 16px;\n  color: #fff;\n  font-weight: 700;\n  border-radius: 8px;\n  cursor: pointer;\n  outline: none;\n}\n.loading {\n  height: 100vh;\n  display: flex;\n  align-items: center;\n  justify-content: center;\n  flex-direction: column;\n}\n\n@keyframes ldio-u6wmgzlxuh9 {\n  0% {\n    transform: rotate(0deg);\n  }\n  50% {\n    transform: rotate(180deg);\n  }\n  100% {\n    transform: rotate(360deg);\n  }\n}\n.ldio-u6wmgzlxuh9 div {\n  position: absolute;\n  animation: ldio-u6wmgzlxuh9 0.91s linear infinite;\n  width: 70px;\n  height: 70px;\n  top: 15px;\n  left: 15px;\n  border-radius: 50%;\n  box-shadow: 0 3.3000000000000003px 0 0 #2196f3;\n  transform-origin: 35px 36.65px;\n}\n.loadingio-spinner-eclipse-tl18qrapo1f {\n  width: 71px;\n  height: 71px;\n  display: inline-block;\n  overflow: hidden;\n  background: transparent;\n}\n.ldio-u6wmgzlxuh9 {\n  width: 100%;\n  height: 100%;\n  position: relative;\n  transform: translateZ(0) scale(0.71);\n  backface-visibility: hidden;\n  transform-origin: 0 0;\n}\n.ldio-u6wmgzlxuh9 div {\n  box-sizing: content-box;\n}\n";

  const styleEl = document.createElement("style");
  const codeEl = document.createTextNode(code);
  styleEl.type = 'text/css';

  styleEl.appendChild(codeEl);
  document.head.appendChild(styleEl);
}